---
- hosts: example
  become: true
  become_method: sudo
  tasks:

  - name: Get the necessary variables
    include_vars:
      file: variables/users.yaml
      name: users_to_add

  - name: Ensure group "{{ item }}" exists
    group:
      name: "{{ item }}"
      state: present
    loop: "{{ groups_to_ensure }}"
    register: groups_exist

  - name: Add groups to sudoers
    lineinfile:
      path: /etc/sudoers
      line: "%{{ item }}    ALL=(ALL)    NOPASSWD: ALL"
      insertbefore: EOF
    loop: "{{ groups_to_ensure }}"

  - name: Add users
    ansible.builtin.user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    loop: "{{ users_to_add['users_to_add'] }}"
    when: groups_exist is succeeded