---

- hosts: example
  become: true
  become_method: sudo
  tasks:

  - name: Get the necessary variables
    include_vars:
      file: ../variables/users.yaml
      name: users_to_add

  - name: Ensure groups exist
    group:
      name: "{{ item }}"
      state: present
    loop: "{{ groups_to_ensure }}"
    register: groups_exist

  - name: Add groups to sudoers
    lineinfile:
      path: /etc/sudoers
      line: "%{{ item }}    ALL=(ALL)    NOPASSWD: ALL"
      insertbefore: EOF
    loop: "{{ groups_to_ensure }}"

  - name: Add users
    ansible.builtin.user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    loop: "{{ users_to_add['users_to_add'] }}"
    when: groups_exist is succeeded
    register: users_added

  - name: Copy authorized keys
    ansible.posix.authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ lookup('file', '../public_keys/{{ item.name }}.pub') }}"
    loop: "{{ users_to_add['users_to_add'] }}"
    when: users_added is succeeded

  
  - name: Get line from sshd config
    command: grep "^AllowUsers " /etc/ssh/sshd_config
    register: old_user_list

  - name: Allow user SSH login
    replace:
      backup: yes
      dest: /etc/ssh/sshd_config
      regexp: '^(AllowUsers(?!.*\b{{ item.name }}\b).*)$'
      replace: '\1 {{ item.name }}'
    when: "{{ item.name not in old_user_list }}"
    loop: "{{ users_to_add['users_to_add'] }}"
    notify:
      - Reload sshd

  handlers:
  - name: Reload sshd
    service:
      name: sshd
      state: reloaded
