---

- hosts: example
  become: true
  become_method: sudo
  tasks:

    - name: Set hostname
      shell: "hostnamectl set-hostname --static {{ new_hostname }}"
      # Shell command was needed due to connection and method call timeouts

    - name: Editing /etc/hosts IPv4
      lineinfile:
        path: /etc/hosts
        search_string: "127.0.0.1"
        line: "127.0.0.1   localhost {{ new_hostname }}"
        state: present
      register: task_result

    - name: Editing /etc/hosts IPv6
      lineinfile:
        path: /etc/hosts
        search_string: "::1"
        line: "::1         localhost {{ new_hostname }}"
        state: present
      register: task_result2

    - name: Get new name
      shell: hostname
      register: changed_hostname
      when: task_result is succeeded and task_result2 is succeeded
  
    - debug:
        var: changed_hostname.stdout_lines